# Premier League Data Cleaning and Combination

This notebook will inspect, clean, and combine Premier League datasets from 2015 through 2025.

In [1]:
import pandas as pd
df_2015 = pd.read_csv("2015.csv")

In [2]:
df_2015.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.5,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/2015,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.5,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/2015,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.0,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/2015,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.5,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/2015,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.0,2.20,2.09,1.82,1.78,1.64,4.07,6.04

In [3]:
df_2015.shape

(380, 65)

In [4]:
df_2015.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH',
       'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5',
       'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH',
       'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='str')

In [5]:
df_2015.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 65 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       380 non-null    str
 1   Date      380 non-null    str
 2   HomeTeam  380 non-null    str
 3   AwayTeam  380 non-null    str
 4   FTHG      380 non-null    int64
 5   FTAG      380 non-null    int64
 6   FTR       380 non-null    str
 7   HTHG      380 non-null    int64
 8   HTAG      380 non-null    int64
 9   HTR       380 non-null    str
 10  Referee   380 non-null    str
 11  HS        380 non-null    int64
 12  AS        380 non-null    int64
 13  HST       380 non-null    int64
 14  AST       380 non-null    int64
 15  HF        380 non-null    int64
 16  AF        380 non-null    int64
 17  HC        380 non-null    int64
 18  AC        380 non-null    int64
 19  HY        380 non-null    int64
 20  AY        380 non-null    int64
 21  HR        380 non-null    int64
 22  AR        380 non-null    int64
 23  B365H     380 non-null    float64
 24  B365D     380 non-null    float64
 25  B365A     380 non-null    float64
 26  BWH       379 non-null    float64
 27  BWD       379 non-null    float64
 28  BWA       379 non-null    float64
 29  IWH       380 non-null    float64
 30  IWD       380 non-null    float64
 31  IWA       380 non-null    float64
 32  LBH       380 non-null    float64
 33  LBD       380 non-null    float64
 34  LBA       380 non-null    float64
 35  PSH       380 non-null    float64
 36  PSD       380 non-null    float64
 37  PSA       380 non-null    float64
 38  WHH       380 non-null    float64
 39  WHD       380 non-null    float64
 40  WHA       380 non-null    float64
 41  VCH       380 non-null    float64
 42  VCD       380 non-null    float64
 43  VCA       380 non-null    float64
 44  Bb1X2     380 non-null    int64
 45  BbMxH     380 non-null    float64
 46  BbAvH     380 non-null    float64
 47  BbMxD     380 non-null    float64
 48  BbAvD     380 non-null    float64
 49  BbMxA     380 non-null    float64
 50  BbAvA     380 non-null    float64
 51  BbOU      380 non-null    int64
 52  BbMx>2.5  380 non-null    float64
 53  BbAv>2.5  380 non-null    float64
 54  BbMx<2.5  380 non-null    float64
 55  BbAv<2.5  380 non-null    float64
 56  BbAH      380 non-null    int64
 57  BbAHh     380 non-null    float64
 58  BbMxAHH   380 non-null    float64
 59  BbAvAHH   380 non-null    float64
 60  BbMxAHA   380 non-null    float64
 61  BbAvAHA   380 non-null    float64
 62  PSCH      380 non-null    float64
 63  PSCD      380 non-null    float64
 64  PSCA      380 non-null    float64
dtypes: float64(39), int64(19), str(7)
memory usage: 193.1 KB

In [6]:
df_2015.isnull().sum()

Div         0
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
           ..
BbMxAHA     0
BbAvAHA     0
PSCH        0
PSCD        0
PSCA        0
Length: 65, dtype: int64

In [7]:
for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    print(year, df.shape)

2015 (380, 65)
2016 (380, 65)
2017 (380, 65)
2018 (380, 62)
2019 (380, 106)
2020 (380, 106)
2021 (380, 106)
2022 (380, 106)
2023 (380, 106)
2024 (380, 120)
2025 (380, 132)

In [8]:
common_columns = None

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    
    if common_columns is None:
        common_columns = set(df.columns)
    else:
        common_columns = common_columns.intersection(df.columns)

print("Number of common columns:", len(common_columns))
print(sorted(common_columns))

Number of common columns: 35
['AC', 'AF', 'AR', 'AS', 'AST', 'AY', 'AwayTeam', 'B365A', 'B365D', 'B365H', 'BWA', 'BWD', 'BWH', 'Date', 'Div', 'FTAG', 'FTHG', 'FTR', 'HC', 'HF', 'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'HTR', 'HY', 'HomeTeam', 'PSA', 'PSCA', 'PSCD', 'PSCH', 'PSD', 'PSH', 'Referee']

In [9]:
for i, column in enumerate(sorted(common_columns), start=1):
    print(i, column)

1 AC
2 AF
3 AR
4 AS
5 AST
6 AY
7 AwayTeam
8 B365A
9 B365D
10 B365H
11 BWA
12 BWD
13 BWH
14 Date
15 Div
16 FTAG
17 FTHG
18 FTR
19 HC
20 HF
21 HR
22 HS
23 HST
24 HTAG
25 HTHG
26 HTR
27 HY
28 HomeTeam
29 PSA
30 PSCA
31 PSCD
32 PSCH
33 PSD
34 PSH
35 Referee

In [10]:
df_2015 = pd.read_csv("2015.csv")

for year in range(2016, 2026):
    df = pd.read_csv(f"{year}.csv")
    
    missing = set(df_2015.columns) - set(df.columns)
    
    print(f"\n{year} - 2015 columns not found:")
    print(sorted(missing))

2016 - 2015 columns not found:
[]

2017 - 2015 columns not found:
[]

2018 - 2015 columns not found:
['LBA', 'LBD', 'LBH']

2019 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'LBA', 'LBD', 'LBH']

2020 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'LBA', 'LBD', 'LBH']

2021 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'LBA', 'LBD', 'LBH']

2022 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'LBA', 'LBD', 'LBH']

2023 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'LBA', 'LBD', 'LBH']

2024 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'IWA', 'IWD', 'IWH', 'LBA', 'LBD', 'LBH', 'VCA', 'VCD', 'VCH']

2025 - 2015 columns not found:
['Bb1X2', 'BbAH', 'BbAHh', 'BbAv<2.5', 'BbAv>2.5', 'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'IWA', 'IWD', 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH']

In [11]:
comparison = []

columns_2015 = set(df_2015.columns)

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    columns_year = set(df.columns)

    comparison.append({
        "Year": year,
        "Total Columns": len(columns_year),
        "Same as 2015": len(columns_2015 & columns_year),
        "Missing from 2015": len(columns_2015 - columns_year),
        "New vs 2015": len(columns_year - columns_2015)
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

    Year  Total Columns  Same as 2015  Missing from 2015  New vs 2015
0   2015             65            65                  0            0
1   2016             65            65                  0            0
2   2017             65            65                  0            0
3   2018             62            62                  3            0
4   2019            106            44                 21           62
5   2020            106            44                 21           62
6   2021            106            44                 21           62
7   2022            106            44                 21           62
8   2023            106            44                 21           62
9   2024            120            38                 27           82
10  2025            132            38                 27           94

In [12]:
required_columns = [
    "Date",
    "HomeTeam", "AwayTeam",
    "FTHG", "FTAG", "FTR",
    "HTHG", "HTAG", "HTR",
    "HS", "AS",
    "HST", "AST",
    "HC", "AC",
    "HF", "AF",
    "HY", "AY",
    "HR", "AR"
]
for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")

    missing = set(required_columns) - set(df.columns)

    print(year, "Missing:", missing)

2015 Missing: set()
2016 Missing: set()
2017 Missing: set()
2018 Missing: set()
2019 Missing: set()
2020 Missing: set()
2021 Missing: set()
2022 Missing: set()
2023 Missing: set()
2024 Missing: set()
2025 Missing: set()

In [13]:
quality_check = []

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    selected = df[required_columns]

    quality_check.append({
        "Year": year,
        "Rows": len(selected),
        "Missing Values": selected.isnull().sum().sum(),
        "Duplicate Rows": selected.duplicated().sum()
    })

quality_df = pd.DataFrame(quality_check)

quality_df

    Year  Rows  Missing Values  Duplicate Rows
0   2015   380               0               0
1   2016   380               0               0
2   2017   380               0               0
3   2018   380               0               0
4   2019   380               0               0
5   2020   380               0               0
6   2021   380               0               0
7   2022   380               0               0
8   2023   380               0               0
9   2024   380               0               0
10  2025   380               0               0

In [14]:
for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    
    print(
        year,
        "FTR:", sorted(df["FTR"].unique()),
        "HTR:", sorted(df["HTR"].unique())
    )

2015 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2016 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2017 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2018 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2019 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2020 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2021 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2022 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2023 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2024 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']
2025 FTR: ['A', 'D', 'H'] HTR: ['A', 'D', 'H']

In [15]:
numeric_columns = [
    "FTHG", "FTAG",
    "HTHG", "HTAG",
    "HS", "AS",
    "HST", "AST",
    "HC", "AC",
    "HF", "AF",
    "HY", "AY",
    "HR", "AR"
]

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    
    non_numeric = df[numeric_columns].select_dtypes(exclude="number").columns
    
    print(year, "Non-numeric columns:", list(non_numeric))

2015 Non-numeric columns: []
2016 Non-numeric columns: []
2017 Non-numeric columns: []
2018 Non-numeric columns: []
2019 Non-numeric columns: []
2020 Non-numeric columns: []
2021 Non-numeric columns: []
2022 Non-numeric columns: []
2023 Non-numeric columns: []
2024 Non-numeric columns: []
2025 Non-numeric columns: []

In [16]:
all_numeric = []

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")
    all_numeric.append(df[numeric_columns])

numeric_combined = pd.concat(all_numeric, ignore_index=True)

ranges = pd.DataFrame({
    "Minimum": numeric_combined.min(),
    "Maximum": numeric_combined.max()
})

ranges

      Minimum  Maximum
FTHG        0        9
FTAG        0        9
HTHG        0        5
HTAG        0        5
HS          0       37
AS          0       37
HST         0       17
AST         0       15
HC          0       19
AC          0       19
HF          0       24
AF          1       26
HY          0        7
AY          0        9
HR          0        2
AR          0        2

In [17]:
consistency_checks = pd.DataFrame({
    "HST > HS": [(numeric_combined["HST"] > numeric_combined["HS"]).sum()],
    "AST > AS": [(numeric_combined["AST"] > numeric_combined["AS"]).sum()],
    "HTHG > FTHG": [(numeric_combined["HTHG"] > numeric_combined["FTHG"]).sum()],
    "HTAG > FTAG": [(numeric_combined["HTAG"] > numeric_combined["FTAG"]).sum()]
})

consistency_checks

   HST > HS  AST > AS  HTHG > FTHG  HTAG > FTAG
0         0         1            0            0

In [18]:
numeric_combined[numeric_combined["AST"] > numeric_combined["AS"]]

      FTHG  FTAG  HTHG  HTAG  HS  AS  HST  AST  HC  AC  HF  AF  HY  AY  HR  AR
2288     2     4     2     1  17   8    3    9   7   6   4   3   1   0   0   0

In [19]:
df_2021.loc[
    df_2021["AST"] > df_2021["AS"],
    ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "HS", "AS", "HST", "AST"]
]

NameError: name 'df_2021' is not defined

In [ ]:
df_2021 = pd.read_csv("2021.csv")

df_2021.loc[
    df_2021["AST"] > df_2021["AS"],
    ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "HS", "AS", "HST", "AST"]
]

         Date   HomeTeam  AwayTeam  FTHG  FTAG  HS  AS  HST  AST
8  15/08/2021  Newcastle  West Ham     2     4  17   8    3    9

Data correction: The Newcastle vs. West Ham match on 15/08/2021 contained an inconsistent value of 8 away shots and 9 away shots on target. Independent match records report 18 West Ham shots and 9 shots on target. The away-shots value was therefore corrected from 8 to 18.

In [ ]:
df_2021.loc[
    (df_2021["Date"] == "15/08/2021") &
    (df_2021["HomeTeam"] == "Newcastle") &
    (df_2021["AwayTeam"] == "West Ham"),
    "AS"
] = 18

In [ ]:
teams = set()

for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")

    teams.update(df["HomeTeam"].unique())
    teams.update(df["AwayTeam"].unique())

print("Number of unique team names:", len(teams))

for team in sorted(teams):
    print(team)

Number of unique team names: 34
Arsenal
Aston Villa
Bournemouth
Brentford
Brighton
Burnley
Cardiff
Chelsea
Crystal Palace
Everton
Fulham
Huddersfield
Hull
Ipswich
Leeds
Leicester
Liverpool
Luton
Man City
Man United
Middlesbrough
Newcastle
Norwich
Nott'm Forest
Sheffield United
Southampton
Stoke
Sunderland
Swansea
Tottenham
Watford
West Brom
West Ham
Wolves

In [ ]:
for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")

    home_spaces = (df["HomeTeam"] != df["HomeTeam"].str.strip()).sum()
    away_spaces = (df["AwayTeam"] != df["AwayTeam"].str.strip()).sum()

    print(year, "Home spaces:", home_spaces, "Away spaces:", away_spaces)

2015 Home spaces: 0 Away spaces: 0
2016 Home spaces: 0 Away spaces: 0
2017 Home spaces: 0 Away spaces: 0
2018 Home spaces: 0 Away spaces: 0
2019 Home spaces: 0 Away spaces: 0
2020 Home spaces: 0 Away spaces: 0
2021 Home spaces: 0 Away spaces: 0
2022 Home spaces: 0 Away spaces: 0
2023 Home spaces: 0 Away spaces: 0
2024 Home spaces: 0 Away spaces: 0
2025 Home spaces: 0 Away spaces: 0

In [ ]:
for year in range(2015, 2026):
    df = pd.read_csv(f"{year}.csv")

    print(
        year,
        "First 3:", df["Date"].head(3).tolist(),
        "Last 3:", df["Date"].tail(3).tolist()
    )

2015 First 3: ['08/08/2015', '08/08/2015', '08/08/2015'] Last 3: ['15/05/2016', '15/05/2016', '17/05/2016']
2016 First 3: ['13/08/16', '13/08/16', '13/08/16'] Last 3: ['21/05/17', '21/05/17', '21/05/17']
2017 First 3: ['11/08/2017', '12/08/2017', '12/08/2017'] Last 3: ['13/05/2018', '13/05/2018', '13/05/2018']
2018 First 3: ['10/08/2018', '11/08/2018', '11/08/2018'] Last 3: ['12/05/2019', '12/05/2019', '12/05/2019']
2019 First 3: ['09/08/2019', '10/08/2019', '10/08/2019'] Last 3: ['26/07/2020', '26/07/2020', '26/07/2020']
2020 First 3: ['12/09/2020', '12/09/2020', '12/09/2020'] Last 3: ['23/05/2021', '23/05/2021', '23/05/2021']
2021 First 3: ['13/08/2021', '14/08/2021', '14/08/2021'] Last 3: ['22/05/2022', '22/05/2022', '22/05/2022']
2022 First 3: ['05/08/2022', '06/08/2022', '06/08/2022'] Last 3: ['28/05/2023', '28/05/2023', '28/05/2023']
2023 First 3: ['11/08/2023', '12/08/2023', '12/08/2023'] Last 3: ['19/05/2024', '19/05/2024', '19/05/2024']
2024 First 3: ['16/08/2024', '17/08/2024', '17/08/2024'] Last 3: ['25/05/2025', '25/05/2025', '25/05/2025']
2025 First 3: ['15/08/2025', '16/08/2025', '16/08/2025'] Last 3: ['24/05/2026', '24/05/2026', '24/05/2026']

In [ ]:
for year in range(2016, 2026):
    df = pd.read_csv(f"{year}.csv")

    parsed_dates = pd.to_datetime(
        df["Date"],
        dayfirst=True,
        errors="coerce"
    )

    print(
        year,
        "Invalid dates:", parsed_dates.isna().sum(),
        "Chronological:", parsed_dates.is_monotonic_increasing
    )

2016 Invalid dates: 0 Chronological: True
2017 Invalid dates: 0 Chronological: True
2018 Invalid dates: 0 Chronological: True
2019 Invalid dates: 0 Chronological: True
2020 Invalid dates: 0 Chronological: True
2021 Invalid dates: 0 Chronological: True
2022 Invalid dates: 0 Chronological: True
2023 Invalid dates: 0 Chronological: True
2024 Invalid dates: 0 Chronological: True
2025 Invalid dates: 0 Chronological: True

C:\Users\Admin\AppData\Local\Temp\ipykernel_3132\2772919369.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed_dates = pd.to_datetime(

In [ ]:
for year in range(2016, 2026):
    season = f"{year}/{str(year + 1)[-2:]}"
    print(year, "->", season)

2016 -> 2016/17
2017 -> 2017/18
2018 -> 2018/19
2019 -> 2019/20
2020 -> 2020/21
2021 -> 2021/22
2022 -> 2022/23
2023 -> 2023/24
2024 -> 2024/25
2025 -> 2025/26

In [ ]:
all_seasons = []

for year in range(2016, 2026):
    df = pd.read_csv(f"{year}.csv")

    # Keep only the columns needed for our research questions
    df = df[required_columns].copy()

    # Create the season label
    df["Season"] = f"{year}/{str(year + 1)[-2:]}"

    all_seasons.append(df)

combined = pd.concat(all_seasons, ignore_index=True)

combined.shape

(3800, 22)

In [ ]:
combined["Date"] = pd.to_datetime(
    combined["Date"],
    dayfirst=True
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_3132\3144071599.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined["Date"] = pd.to_datetime(

In [ ]:
combined["Date"].dtype

dtype('<M8[us]')

In [ ]:
combined[["Date", "Season"]].head()

        Date   Season
0 2016-08-13  2016/17
1 2016-08-13  2016/17
2 2016-08-13  2016/17
3 2016-08-13  2016/17
4 2016-08-13  2016/17

In [ ]:
combined.loc[
    (combined["Date"] == "2021-08-15") &
    (combined["HomeTeam"] == "Newcastle") &
    (combined["AwayTeam"] == "West Ham"),
    "AS"
] = 18

In [ ]:
combined.loc[
    (combined["Date"] == "2021-08-15") &
    (combined["HomeTeam"] == "Newcastle") &
    (combined["AwayTeam"] == "West Ham"),
    ["Date", "Season", "HomeTeam", "AwayTeam", "AS", "AST"]
]

           Date   Season   HomeTeam  AwayTeam  AS  AST
1908 2021-08-15  2021/22  Newcastle  West Ham  18    9

In [ ]:
final_check = pd.DataFrame({
    "Rows": [len(combined)],
    "Columns": [len(combined.columns)],
    "Missing Values": [combined.isnull().sum().sum()],
    "Duplicate Rows": [combined.duplicated().sum()],
    "HST > HS": [(combined["HST"] > combined["HS"]).sum()],
    "AST > AS": [(combined["AST"] > combined["AS"]).sum()],
    "HTHG > FTHG": [(combined["HTHG"] > combined["FTHG"]).sum()],
    "HTAG > FTAG": [(combined["HTAG"] > combined["FTAG"]).sum()]
})

final_check

,Rows,Columns,Missing Values,Duplicate Rows,HST > HS,AST > AS,HTHG > FTHG,HTAG > FTAG
0,3800,22,0,0,0,0,0,0

In [ ]:
combined.to_csv("premier_league_cleaned_2016_2025.csv", index=False)

In [ ]:
check_saved = pd.read_csv("premier_league_cleaned_2016_2025.csv")

check_saved.shape

(3800, 22)

In [ ]:
combined.to_excel(
    "premier_league_cleaned_2016_2025.xlsx",
    index=False
)