In [100]:
import pandas as pd
players_2016 = pd.read_csv(
    "raw_player_data/2016-17_all_players_gw.csv"
)

In [101]:
players_2016.shape

(23679, 56)

In [102]:
players_2016.columns.tolist()

['name',
 'assists',
 'attempted_passes',
 'big_chances_created',
 'big_chances_missed',
 'bonus',
 'bps',
 'clean_sheets',
 'clearances_blocks_interceptions',
 'completed_passes',
 'creativity',
 'dribbles',
 'ea_index',
 'element',
 'errors_leading_to_goal',
 'errors_leading_to_goal_attempt',
 'fixture',
 'fouls',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'id',
 'influence',
 'key_passes',
 'kickoff_time',
 'kickoff_time_formatted',
 'loaned_in',
 'loaned_out',
 'minutes',
 'offside',
 'open_play_crosses',
 'opponent_team',
 'own_goals',
 'penalties_conceded',
 'penalties_missed',
 'penalties_saved',
 'recoveries',
 'red_cards',
 'round',
 'saves',
 'selected',
 'tackled',
 'tackles',
 'target_missed',
 'team_a_score',
 'team_h_score',
 'threat',
 'total_points',
 'transfers_balance',
 'transfers_in',
 'transfers_out',
 'value',
 'was_home',
 'winning_goals',
 'yellow_cards',
 'GW']

In [103]:
players_2016.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,...,0,1,0,0,0,60,True,0,0,1
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,...,23,2,0,0,0,80,True,0,0,1
3,Abdoulaye_Doucour�,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,50,False,0,0,1
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,True,0,0,1

In [104]:
players_2016[
    ["name", "element", "fixture", "minutes",
     "was_home", "goals_scored", "goals_conceded", "GW"]
].head(20)

,name,element,fixture,minutes,was_home,goals_scored,goals_conceded,GW
0,Aaron_Cresswell,454,10,0,False,0,0,1
1,Aaron_Lennon,142,3,15,True,0,0,1
2,Aaron_Ramsey,16,8,60,True,0,3,1
3,Abdoulaye_Doucour�,482,7,0,False,0,0,1
4,Abdul Rahman_Baba,80,10,0,True,0,0,1
5,Abel_Hern�ndez,163,4,90,True,0,1,1
6,Adama_Diomande,164,4,90,True,1,1,1
7,Adam_Clayton,283,6,90,True,0,1,1
8,Adam_Federici,30,9,0,True,0,0,1
9,Adam_Forshaw,286,6,69,True,0,1,1
10,Adam_Lallana,205,8,75,False,1,3,1
11,Adam_Matthews,345,5,0,False,0,0,1
12,Adam_Reach,285,6,0,True,0,0,1
13,Adam_Smith,34,9,90,True,1,3,1
14,Adl�ne_Gu�dioura,415,7,72,False,0,1,1
15,Adnan_Januzaj,261,5,27,False,0,1,1
16,Adri�n_San Miguel del Castillo,450,10,90,False,0,2,1
17,Ahmed_Elmohamady,158,4,90,True,0,1,1
18,Ahmed_Musa,187,4,90,False,0,2,1
19,Alberto_Moreno,192,8,90,False,0,3,1

In [105]:
for column in players_2016.columns:
    print(column)

name
assists
attempted_passes
big_chances_created
big_chances_missed
bonus
bps
clean_sheets
clearances_blocks_interceptions
completed_passes
creativity
dribbles
ea_index
element
errors_leading_to_goal
errors_leading_to_goal_attempt
fixture
fouls
goals_conceded
goals_scored
ict_index
id
influence
key_passes
kickoff_time
kickoff_time_formatted
loaned_in
loaned_out
minutes
offside
open_play_crosses
opponent_team
own_goals
penalties_conceded
penalties_missed
penalties_saved
recoveries
red_cards
round
saves
selected
tackled
tackles
target_missed
team_a_score
team_h_score
threat
total_points
transfers_balance
transfers_in
transfers_out
value
was_home
winning_goals
yellow_cards
GW

In [106]:
for column in players_2016.columns:
    print(column)

name
assists
attempted_passes
big_chances_created
big_chances_missed
bonus
bps
clean_sheets
clearances_blocks_interceptions
completed_passes
creativity
dribbles
ea_index
element
errors_leading_to_goal
errors_leading_to_goal_attempt
fixture
fouls
goals_conceded
goals_scored
ict_index
id
influence
key_passes
kickoff_time
kickoff_time_formatted
loaned_in
loaned_out
minutes
offside
open_play_crosses
opponent_team
own_goals
penalties_conceded
penalties_missed
penalties_saved
recoveries
red_cards
round
saves
selected
tackled
tackles
target_missed
team_a_score
team_h_score
threat
total_points
transfers_balance
transfers_in
transfers_out
value
was_home
winning_goals
yellow_cards
GW

In [107]:
[column for column in players_2016.columns if "team" in column.lower()]

['opponent_team', 'team_a_score', 'team_h_score']

In [108]:
fixture_4 = players_2016[
    players_2016["fixture"] == 4
]

fixture_4[
    ["name", "element", "minutes", "was_home",
     "opponent_team", "team_h_score", "team_a_score"]
]

,name,element,minutes,was_home,opponent_team,team_h_score,team_a_score
5,Abel_Hern�ndez,163,90,True,8,2,1
6,Adama_Diomande,164,90,True,8,2,1
17,Ahmed_Elmohamady,158,90,True,8,2,1
18,Ahmed_Musa,187,90,False,7,2,1
25,Alex_Bruce,154,0,True,8,2,1
31,Allan_McGregor,146,0,True,8,2,1
35,Andrew_Robertson,152,90,True,8,2,1
41,Andy_King,178,67,False,7,2,1
58,Bartosz_Kapustka,497,0,False,7,2,1
61,Benjamin_Chilwell,496,0,False,7,2,1
77,Brian_Lenihan,148,0,True,8,2,1
95,Christian_Fuchs,168,90,False,7,2,1
113,Curtis_Davies,149,90,True,8,2,1
119,Daniel_Amartey,182,23,False,7,2,1
121,Daniel_Drinkwater,179,90,False,7,2,1
126,Danny_Simpson,172,82,False,7,2,1
134,David_Meyler,161,90,True,8,2,1
141,Demarai_Gray,181,67,False,7,2,1
150,Dusan_Kuciak,517,0,True,8,2,1
153,Eldin_Jakupovic,147,90,True,8,2,1
194,Greg_Luer,518,0,True,8,2,1
195,Greg_Olley,514,0,True,8,2,1
198,G�khan_Inler,180,0,False,7,2,1
203,Harry_Maguire,153,0,True,8,2,1
221,Jake_Livermore,157,90,True,8,2,1
234,Jamie_Vardy,184,90,False,7,2,1
237,Jarrod_Bowen,516,0,True,8,2,1
243,Jeffrey_Schlupp,169,0,False,7,2,1
281,Josh_Clackstone,515,0,True,8,2,1
283,Josh_Tymon,519,0,True,8,2,1
294,Kasper_Schmeichel,165,90,False,7,2,1
313,Leonardo_Ulloa,185,8,False,7,2,1
321,Luis_Hern�ndez,175,90,False,7,2,1
333,Marcin_Wasilewski,170,0,False,7,2,1
337,Marc_Albrighton,177,0,False,7,2,1
364,Michael_Dawson,150,0,True,8,2,1
374,Mohamed_Diam�,159,0,True,8,2,1
377,Moses_Odubajo,151,0,True,8,2,1
384,Nampalys_Mendy,183,0,False,7,2,1
429,Ritchie_de Laet,171,0,False,7,2,1
430,Riyad_Mahrez,176,90,False,7,2,1
433,Robert_Huth,173,0,False,7,2,1
434,Robert_Snodgrass,155,90,True,8,2,1
437,Ron-Robert_Zieler,166,0,False,7,2,1
449,Sam_Clucas,156,90,True,8,2,1
463,Shaun_Maloney,162,0,True,8,2,1
465,Shinji_Okazaki,186,23,False,7,2,1
492,Tom_Huddlestone,160,90,True,8,2,1
510,Wes_Morgan,167,90,False,7,2,1
519,Yohan_Benalouane,174,0,False,7,2,1

In [109]:
players_2016[
    ["opponent_team", "was_home"]
].drop_duplicates().sort_values("opponent_team")

      opponent_team  was_home
10                1     False
536               1      True
531               2      True
33                2     False
43                3     False
563               3      True
0                 4     False
556               4      True
63                5     False
1143              5      True
1126              6      True
29                6     False
18                7     False
527               7      True
5                 8      True
1158              8     False
1125              9     False
2                 9      True
560              10      True
11               10     False
545              11     False
8                11      True
71               12     False
1147             12      True
1127             13      True
3                13     False
559              14     False
7                14      True
21               15      True
526              15     False
37               16      True
1161             16     False
544              17     False
1                17      True
27               18      True
529              18     False
38               19      True
549              19     False
4                20      True
1203             20     False

In [110]:
players_2016[
    ["name", "id", "element", "fixture", "opponent_team", "was_home", "minutes"]
].head(20)

,name,id,element,fixture,opponent_team,was_home,minutes
0,Aaron_Cresswell,454,454,10,4,False,0
1,Aaron_Lennon,142,142,3,17,True,15
2,Aaron_Ramsey,16,16,8,9,True,60
3,Abdoulaye_Doucour�,482,482,7,13,False,0
4,Abdul Rahman_Baba,80,80,10,20,True,0
5,Abel_Hern�ndez,163,163,4,8,True,90
6,Adama_Diomande,164,164,4,8,True,90
7,Adam_Clayton,283,283,6,14,True,90
8,Adam_Federici,30,30,9,11,True,0
9,Adam_Forshaw,286,286,6,14,True,69
10,Adam_Lallana,205,205,8,1,False,75
11,Adam_Matthews,345,345,5,10,False,0
12,Adam_Reach,285,285,6,14,True,0
13,Adam_Smith,34,34,9,11,True,90
14,Adl�ne_Gu�dioura,415,415,7,13,False,72
15,Adnan_Januzaj,261,261,5,10,False,27
16,Adri�n_San Miguel del Castillo,450,450,10,4,False,90
17,Ahmed_Elmohamady,158,158,4,8,True,90
18,Ahmed_Musa,187,187,4,7,False,90
19,Alberto_Moreno,192,192,8,1,False,90

In [111]:
players_2016["opponent_team"].nunique()

20

In [112]:
players_2016 = pd.read_csv(
    "raw_player_data/merged_gw.csv",
    encoding="latin1"
)

player_info_2016 = pd.read_csv(
    "raw_player_data/players_raw.csv"
)

FileNotFoundError: [Errno 2] No such file or directory: 'raw_player_data/merged_gw.csv'

In [ ]:
players_2016.shape

(23679, 56)

In [ ]:
player_info_2016.shape

(683, 57)

In [ ]:
players_2016[
    players_2016["element"] == 158
][["name", "element", "fixture", "minutes"]].head()

                  name  element  fixture  minutes
17    Ahmed_Elmohamady      158        4       90
543   Ahmed_Elmohamady      158       99       90
1141  Ahmed_Elmohamady      158      105       90
1740  Ahmed_Elmohamady      158      117       90
2341  Ahmed_Elmohamady      158      124       90

In [ ]:
player_info_2016[
    player_info_2016["id"] == 158
][["id", "first_name", "second_name", "team"]]

      id first_name second_name  team
157  158      Ahmed  Elmohamady     7

In [ ]:
players_2016_merged = players_2016.merge(
    player_info_2016[["id", "team"]],
    left_on="element",
    right_on="id",
    how="left"
)

In [ ]:
players_2016_merged.shape

(23679, 58)

In [ ]:
players_2016_merged["team"].isna().sum()

np.int64(0)

In [ ]:
players_2016_merged[
    players_2016_merged["fixture"] == 4
][
    ["name", "team", "opponent_team",
     "was_home", "minutes", "team_h_score", "team_a_score"]
].head(20)

,name,team,opponent_team,was_home,minutes,team_h_score,team_a_score
5,Abel_Hernández,7,8,True,90,2,1
6,Adama_Diomande,7,8,True,90,2,1
17,Ahmed_Elmohamady,7,8,True,90,2,1
18,Ahmed_Musa,8,7,False,90,2,1
25,Alex_Bruce,7,8,True,0,2,1
31,Allan_McGregor,7,8,True,0,2,1
35,Andrew_Robertson,7,8,True,90,2,1
41,Andy_King,8,7,False,67,2,1
58,Bartosz_Kapustka,8,7,False,0,2,1
61,Benjamin_Chilwell,8,7,False,0,2,1
77,Brian_Lenihan,7,8,True,0,2,1
95,Christian_Fuchs,8,7,False,90,2,1
113,Curtis_Davies,7,8,True,90,2,1
119,Daniel_Amartey,8,7,False,23,2,1
121,Daniel_Drinkwater,8,7,False,90,2,1
126,Danny_Simpson,8,7,False,82,2,1
134,David_Meyler,7,8,True,90,2,1
141,Demarai_Gray,8,7,False,67,2,1
150,Dusan_Kuciak,7,8,True,0,2,1
153,Eldin_Jakupovic,7,8,True,90,2,1

In [ ]:
[column for column in player_info_2016.columns if "team" in column.lower()]

['dreamteam_count', 'in_dreamteam', 'team', 'team_code']

In [ ]:
teams = pd.read_csv(
    "raw_player_data/master_team_list.csv"
)

In [ ]:
teams.shape

(160, 3)

In [ ]:
teams.head()

    season  team       team_name
0  2016-17     1         Arsenal
1  2016-17     2     Bournemouth
2  2016-17     3         Burnley
3  2016-17     4         Chelsea
4  2016-17     5  Crystal Palace

In [ ]:
players_2016_merged["season"] = "2016-17"

In [ ]:
players_2016_merged[
    ["name", "team", "season"]
].head()

                 name  team   season
0     Aaron_Cresswell    20  2016-17
1        Aaron_Lennon     6  2016-17
2        Aaron_Ramsey     1  2016-17
3  Abdoulaye_Doucouré    18  2016-17
4   Abdul Rahman_Baba     4  2016-17

In [ ]:
players_2016_merged = players_2016_merged.merge(
    teams,
    on=["season", "team"],
    how="left"
)

In [ ]:
players_2016_merged.shape

(23679, 60)

In [ ]:
players_2016_merged["team_name"].isna().sum()

np.int64(0)

In [ ]:
players_2016_merged[
    players_2016_merged["fixture"] == 4
][
    ["name", "team_name", "opponent_team",
     "was_home", "minutes", "team_h_score", "team_a_score"]
].head(20)

,name,team_name,opponent_team,was_home,minutes,team_h_score,team_a_score
5,Abel_Hernández,Hull,8,True,90,2,1
6,Adama_Diomande,Hull,8,True,90,2,1
17,Ahmed_Elmohamady,Hull,8,True,90,2,1
18,Ahmed_Musa,Leicester,7,False,90,2,1
25,Alex_Bruce,Hull,8,True,0,2,1
31,Allan_McGregor,Hull,8,True,0,2,1
35,Andrew_Robertson,Hull,8,True,90,2,1
41,Andy_King,Leicester,7,False,67,2,1
58,Bartosz_Kapustka,Leicester,7,False,0,2,1
61,Benjamin_Chilwell,Leicester,7,False,0,2,1
77,Brian_Lenihan,Hull,8,True,0,2,1
95,Christian_Fuchs,Leicester,7,False,90,2,1
113,Curtis_Davies,Hull,8,True,90,2,1
119,Daniel_Amartey,Leicester,7,False,23,2,1
121,Daniel_Drinkwater,Leicester,7,False,90,2,1
126,Danny_Simpson,Leicester,7,False,82,2,1
134,David_Meyler,Hull,8,True,90,2,1
141,Demarai_Gray,Leicester,7,False,67,2,1
150,Dusan_Kuciak,Hull,8,True,0,2,1
153,Eldin_Jakupovic,Hull,8,True,90,2,1

In [ ]:
players_2016_merged["team_name"].isna().sum()

np.int64(0)

In [ ]:
def get_result(row):
    if row["was_home"]:
        if row["team_h_score"] > row["team_a_score"]:
            return "Win"
        elif row["team_h_score"] < row["team_a_score"]:
            return "Loss"
        else:
            return "Draw"

In [ ]:
def get_result(row):
    if row["was_home"]:
        if row["team_h_score"] > row["team_a_score"]:
            return "Win"
        elif row["team_h_score"] < row["team_a_score"]:
            return "Loss"
        else:
            return "Draw"
    else:
        if row["team_h_score"] < row["team_a_score"]:
            return "Win"
        elif row["team_h_score"] > row["team_a_score"]:
            return "Loss"
        else:
            return "Draw"

In [ ]:
players_2016_merged["result"] = players_2016_merged.apply(
    get_result,
    axis=1
)

In [ ]:
players_2016_merged[
    players_2016_merged["fixture"] == 4
][
    ["name", "team_name", "was_home",
     "team_h_score", "team_a_score", "result"]
].head(20)

                  name  team_name  was_home  team_h_score  team_a_score result
5       Abel_Hernández       Hull      True             2             1    Win
6       Adama_Diomande       Hull      True             2             1    Win
17    Ahmed_Elmohamady       Hull      True             2             1    Win
18          Ahmed_Musa  Leicester     False             2             1   Loss
25          Alex_Bruce       Hull      True             2             1    Win
31      Allan_McGregor       Hull      True             2             1    Win
35    Andrew_Robertson       Hull      True             2             1    Win
41           Andy_King  Leicester     False             2             1   Loss
58    Bartosz_Kapustka  Leicester     False             2             1   Loss
61   Benjamin_Chilwell  Leicester     False             2             1   Loss
77       Brian_Lenihan       Hull      True             2             1    Win
95     Christian_Fuchs  Leicester     False             2             1   Loss
113      Curtis_Davies       Hull      True             2             1    Win
119     Daniel_Amartey  Leicester     False             2             1   Loss
121  Daniel_Drinkwater  Leicester     False             2             1   Loss
126      Danny_Simpson  Leicester     False             2             1   Loss
134       David_Meyler       Hull      True             2             1    Win
141       Demarai_Gray  Leicester     False             2             1   Loss
150       Dusan_Kuciak       Hull      True             2             1    Win
153    Eldin_Jakupovic       Hull      True             2             1    Win

In [ ]:
players_2016_merged["result"].value_counts()

result
Loss    9324
Win     9179
Draw    5176
Name: count, dtype: int64

In [ ]:
players_2017 = pd.read_csv(
    "raw_player_data/2017_merged_gw (1).csv",
    encoding="latin1"
)

player_info_2017 = pd.read_csv(
    "raw_player_data/2017_players_raw (1).csv",
    encoding="latin1"
)

In [ ]:
print(players_2017.shape)
print(player_info_2017.shape)

(22467, 56)
(647, 58)

In [ ]:
print(players_2017.columns.tolist())

['name', 'assists', 'attempted_passes', 'big_chances_created', 'big_chances_missed', 'bonus', 'bps', 'clean_sheets', 'clearances_blocks_interceptions', 'completed_passes', 'creativity', 'dribbles', 'ea_index', 'element', 'errors_leading_to_goal', 'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'influence', 'key_passes', 'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out', 'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals', 'penalties_conceded', 'penalties_missed', 'penalties_saved', 'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled', 'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat', 'total_points', 'transfers_balance', 'transfers_in', 'transfers_out', 'value', 'was_home', 'winning_goals', 'yellow_cards', 'GW']

In [ ]:
print(player_info_2017.columns.tolist())

['assists', 'bonus', 'bps', 'chance_of_playing_next_round', 'chance_of_playing_this_round', 'clean_sheets', 'code', 'cost_change_event', 'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall', 'creativity', 'dreamteam_count', 'ea_index', 'element_type', 'ep_next', 'ep_this', 'event_points', 'first_name', 'form', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'in_dreamteam', 'influence', 'loaned_in', 'loaned_out', 'loans_in', 'loans_out', 'minutes', 'news', 'news_added', 'now_cost', 'own_goals', 'penalties_missed', 'penalties_saved', 'photo', 'points_per_game', 'red_cards', 'saves', 'second_name', 'selected_by_percent', 'special', 'squad_number', 'status', 'team', 'team_code', 'threat', 'total_points', 'transfers_in', 'transfers_in_event', 'transfers_out', 'transfers_out_event', 'value_form', 'value_season', 'web_name', 'yellow_cards']

In [ ]:
required_player_columns = [
    "element",
    "fixture",
    "minutes",
    "was_home",
    "opponent_team",
    "team_h_score",
    "team_a_score"
]

for column in required_player_columns:
    print(column, column in players_2017.columns)

element True
fixture True
minutes True
was_home True
opponent_team True
team_h_score True
team_a_score True

In [ ]:
required_info_columns = [
    "id",
    "first_name",
    "second_name",
    "team"
]

for column in required_info_columns:
    print(column, column in player_info_2017.columns)

id True
first_name True
second_name True
team True

In [ ]:
players_2017_merged = players_2017.merge(
    player_info_2017[["id", "team"]],
    left_on="element",
    right_on="id",
    how="left"
)

In [ ]:
players_2017_merged.shape
players_2017_merged["team"].isna().sum()

np.int64(0)

In [ ]:
print(players_2017.shape)
print(players_2017_merged.shape)

(22467, 56)
(22467, 58)

In [ ]:
players_2017_merged["fixture"].nunique()

380

In [ ]:
season_files = {
    "2016-17": ("2016_merged_gw.csv", "2016_players_raw.csv"),
    "2017-18": ("2017-18_merged_gw (1).csv", "2017-18_players_raw (1).csv"),
    "2018-19": ("2018-19_merged_gw (2).csv", "2018-19_players_raw (2).csv"),
    "2019-20": ("2019-20_merged_gw (3).csv", "2019-20_players_raw (3).csv"),
    "2020-21": ("2020-21_merged_gw (4).csv", "2020-21_players_raw (4).csv"),
    "2021-22": ("2021-22_merged_gw (5).csv", "2021-22_players_raw (5).csv"),
    "2022-23": ("2022-23_merged_gw (6).csv", "2022-23_players_raw (6).csv"),
    "2023-24": ("2023-24_merged_gw (7).csv", "2023-24_players_raw (7).csv"),
    "2024-25": ("2024-25_merged_gw (8).csv", "2024-25_players_raw (8).csv"),
    "2025-26": ("2025-26_merged_gw (9).csv", "2025-26_players_raw (9).csv")
}

In [ ]:
season_files["2018-19"]

('2018-19_merged_gw (2).csv', '2018-19_players_raw (2).csv')

In [ ]:
for season, files in season_files.items():
    gw_file, player_file = files

    gw = pd.read_csv(
        f"raw_player_data/{gw_file}",
        encoding="latin1"
    )

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    print(season, gw.shape, player_info.shape)

2016-17 (23679, 56) (683, 57)
2017-18 (22467, 56) (647, 58)
2018-19 (21790, 56) (624, 58)
2019-20 (22560, 33) (666, 61)
2020-21 (24365, 36) (713, 67)
2021-22 (25447, 36) (737, 67)
2022-23 (26505, 41) (778, 88)
2023-24 (29725, 41) (865, 88)
2024-25 (27605, 49) (804, 103)
2025-26 (29757, 46) (841, 105)

In [ ]:
required_player_columns = [
    "name",
    "element",
    "fixture",
    "minutes",
    "was_home",
    "opponent_team",
    "team_h_score",
    "team_a_score"
]

In [ ]:
required_info_columns = [
    "id",
    "first_name",
    "second_name",
    "team"
]

for season, files in season_files.items():

    player_file = files[1]

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    print(season)

    for column in required_info_columns:
        print(column, column in player_info.columns)

2016-17
id True
first_name True
second_name True
team True
2017-18
id True
first_name True
second_name True
team True
2018-19
id True
first_name True
second_name True
team True
2019-20
id True
first_name True
second_name True
team True
2020-21
id True
first_name True
second_name True
team True
2021-22
id True
first_name True
second_name True
team True
2022-23
id True
first_name True
second_name True
team True
2023-24
id True
first_name True
second_name True
team True
2024-25
id True
first_name True
second_name True
team True
2025-26
id True
first_name True
second_name True
team True

In [ ]:
all_seasons = []

for season, files in season_files.items():
    gw_file, player_file = files

    # Load the two files for this season
    gw = pd.read_csv(
        f"raw_player_data/{gw_file}",
        encoding="latin1"
    )

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    # Older files do not have the player's team,
    # so get it from the player information file
    if "team" not in gw.columns:
        season_merged = gw.merge(
            player_info[["id", "team"]],
            left_on="element",
            right_on="id",
            how="left"
        )
    else:
        # Newer files already contain team
        season_merged = gw.copy()

    # Identify which season these rows came from
    season_merged["season"] = season

    # Store this completed season
    all_seasons.append(season_merged)

    # Check our work
    print(
        season,
        season_merged.shape,
        season_merged["team"].isna().sum()
    )

2016-17 (23679, 59) 0
2017-18 (22467, 59) 0
2018-19 (21790, 59) 0
2019-20 (22560, 36) 0
2020-21 (24365, 37) 0
2021-22 (25447, 37) 0
2022-23 (26505, 42) 0
2023-24 (29725, 42) 0
2024-25 (27605, 50) 0
2025-26 (29757, 47) 0

In [ ]:
gw = pd.read_csv(
    "raw_player_data/2020-21_merged_gw (4).csv",
    encoding="latin1"
)

[column for column in gw.columns if "team" in column.lower()]

['team', 'opponent_team', 'team_a_score', 'team_h_score']

In [ ]:
players_combined = pd.concat(
    all_seasons,
    ignore_index=True
)

players_combined.shape

(253900, 76)

In [ ]:
players_combined["season"].value_counts().sort_index()

season
2016-17    23679
2017-18    22467
2018-19    21790
2019-20    22560
2020-21    24365
2021-22    25447
2022-23    26505
2023-24    29725
2024-25    27605
2025-26    29757
Name: count, dtype: int64

In [ ]:
players_combined.groupby("season")["fixture"].nunique()

season
2016-17    380
2017-18    380
2018-19    380
2019-20    380
2020-21    380
2021-22    380
2022-23    380
2023-24    380
2024-25    380
2025-26    380
Name: fixture, dtype: int64

In [ ]:
players_combined.isna().sum().sort_values(ascending=False)

mng_loss             240473
mng_win              240473
mng_clean_sheets     240473
mng_underdog_draw    240473
mng_draw             240473
                      ...
GW                        0
was_home                  0
transfers_in              0
transfers_out             0
value                     0
Length: 76, dtype: int64

In [ ]:
complete_columns = players_combined.columns[
    players_combined.isna().sum() == 0
]

complete_columns.tolist()

['name',
 'assists',
 'bonus',
 'bps',
 'clean_sheets',
 'creativity',
 'element',
 'fixture',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'influence',
 'kickoff_time',
 'minutes',
 'opponent_team',
 'own_goals',
 'penalties_missed',
 'penalties_saved',
 'red_cards',
 'round',
 'saves',
 'selected',
 'threat',
 'total_points',
 'transfers_balance',
 'transfers_in',
 'transfers_out',
 'value',
 'was_home',
 'yellow_cards',
 'GW',
 'team',
 'season']

In [ ]:
analysis_columns = [
    "season",
    "fixture",
    "kickoff_time",
    "team",
    "opponent_team",
    "was_home",
    "element",
    "name",
    "minutes",
    "goals_scored",
    "assists",
    "goals_conceded",
    "clean_sheets",
    "total_points"
]

players_analysis = players_combined[analysis_columns].copy()

players_analysis.shape

(253900, 14)

In [ ]:
print("Did not play:", (players_analysis["minutes"] == 0).sum())
print("Played:", (players_analysis["minutes"] > 0).sum())

Did not play: 145213
Played: 108687

In [ ]:
players_played = players_analysis[
    players_analysis["minutes"] > 0
].copy()

players_played.shape

(108687, 14)

In [ ]:
players_combined[
    ["team_h_score", "team_a_score"]
].isna().sum()

team_h_score    59
team_a_score    59
dtype: int64

In [ ]:
missing_scores = players_combined[
    players_combined["team_h_score"].isna() |
    players_combined["team_a_score"].isna()
]

missing_scores[
    ["season", "fixture", "kickoff_time", "team",
     "opponent_team", "was_home", "name", "minutes"]
]

,season,fixture,kickoff_time,team,opponent_team,was_home,name,minutes
83810,2019-20,275,2020-03-11T19:30:00Z,11,1,True,John_Stones_207,0
83812,2019-20,275,2020-03-11T19:30:00Z,11,1,True,David_Silva_219,0
83814,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Bukayo_Saka_541,0
83816,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Sead_Kolasinac_3,0
83836,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Bernd_Leno_14,0
83842,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Kyle_Walker_203,0
83845,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Pierre-Emerick_Aubameyang_11,0
83852,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Kieran_Tierney_515,0
83860,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Edward_Nketiah_13,0
83884,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Daniel_Ceballos FernÃ¡ndez_469,0
83892,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Pablo_MarÃ­_617,0
83896,2019-20,275,2020-03-11T19:30:00Z,11,1,True,JoÃ£o Pedro Cavaco_Cancelo_518,0
83902,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Rodrigo_Hernandez_443,0
83911,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Sokratis_Papastathopoulos_5,0
83918,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Emiliano_MartÃ­nez_427,0
83923,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Gabriel Fernando_de Jesus_211,0
83928,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Phil_Foden_220,0
83942,2019-20,275,2020-03-11T19:30:00Z,11,1,True,NicolÃ¡s_Otamendi_208,0
83960,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Riyad_Mahrez_217,0
83980,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Sergio_AgÃ¼ero_210,0
83994,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Ainsley_Maitland-Niles_4,0
84011,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Ilkay_GÃ¼ndogan_222,0
84014,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Scott_Carson_562,0
84034,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Gabriel Teodoro_Martinelli Silva_504,0
84049,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Joseph_Willock_490,0
84067,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Nicolas_PÃ©pÃ©_488,0
84075,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Benjamin_Mendy_204,0
84077,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Emile_Smith Rowe_576,0
84080,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Reiss_Nelson_489,0
84083,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Claudio_Bravo_213,0
84094,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Nacho_Monreal_6,0
84119,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Mesut_Ãzil_15,0
84121,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Eric_Garcia_544,0
84153,2019-20,275,2020-03-11T19:30:00Z,1,11,False,CÃ©dric_Soares_486,0
84164,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Granit_Xhaka_18,0
84171,2019-20,275,2020-03-11T19:30:00Z,11,1,True,JosÃ© Ãngel_EsmorÃ­s Tasende_440,0
84176,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Raheem_Sterling_214,0
84192,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Shkodran_Mustafi_1,0
84208,2019-20,275,2020-03-11T19:30:00Z,1,11,False,David_Luiz Moreira Marinho_106,0
84220,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Kevin_De Bruyne_215,0
84227,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Aymeric_Laporte_202,0
84242,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Henrikh_Mkhitaryan_16,0
84244,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Mohamed_Elneny_20,0
84255,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Rob_Holding_10,0
84266,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Alexandre_Lacazette_12,0
84268,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Laurent_Koscielny_7,0
84287,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Ederson_Santana de Moraes_212,0
84311,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Calum_Chambers_467,0
84345,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Carl_Jenkinson_9,0
84355,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Konstantinos_Mavropanos_8,0
84376,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Fernando_Luiz Rosa_221,0
84387,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Matteo_Guendouzi_21,0
84391,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Bernardo Mota_Veiga de Carvalho e Silva_218,0
84393,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Oleksandr_Zinchenko_206,0
84432,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Danilo Luiz_da Silva_209,0
84435,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Lucas_Torreira_19,0
84439,2019-20,275,2020-03-11T19:30:00Z,1,11,False,Tyreece_John-Jules_585,0
84447,2019-20,275,2020-03-11T19:30:00Z,11,1,True,Leroy_SanÃ©_216,0
84457,2019-20,275,2020-03-11T19:30:00Z,1,11,False,HÃ©ctor_BellerÃ­n_2,0

In [ ]:
players_combined[
    players_combined["minutes"] > 0
][["team_h_score", "team_a_score"]].isna().sum()

team_h_score    0
team_a_score    0
dtype: int64

In [ ]:
analysis_columns = [
    "season",
    "fixture",
    "kickoff_time",
    "team",
    "opponent_team",
    "was_home",
    "team_h_score",
    "team_a_score",
    "element",
    "name",
    "minutes",
    "goals_scored",
    "assists",
    "goals_conceded",
    "clean_sheets",
    "total_points"
]

players_analysis = players_combined[analysis_columns].copy()

players_analysis.shape

(253900, 16)

In [ ]:
players_played = players_analysis[
    players_analysis["minutes"] > 0
].copy()

players_played.shape

(108687, 16)

In [ ]:
def get_result(row):
    if row["team_h_score"] == row["team_a_score"]:
        return "D"

    elif row["was_home"] == True and row["team_h_score"] > row["team_a_score"]:
        return "W"

    elif row["was_home"] == True and row["team_h_score"] < row["team_a_score"]:
        return "L"

    elif row["was_home"] == False and row["team_a_score"] > row["team_h_score"]:
        return "W"

    elif row["was_home"] == False and row["team_a_score"] < row["team_h_score"]:
        return "L"

players_played["result"] = players_played.apply(
    get_result,
    axis=1
)

In [ ]:
players_played["result"].value_counts()

KeyError: 'result'

In [ ]:
players_played.columns

Index(['season', 'fixture', 'kickoff_time', 'team', 'opponent_team',
       'was_home', 'team_h_score', 'team_a_score', 'element', 'name',
       'minutes', 'goals_scored', 'assists', 'goals_conceded', 'clean_sheets',
       'total_points'],
      dtype='str')

In [ ]:
def get_result(row):
    if row["team_h_score"] == row["team_a_score"]:
        return "D"

    elif row["was_home"] == True and row["team_h_score"] > row["team_a_score"]:
        return "W"

    elif row["was_home"] == True and row["team_h_score"] < row["team_a_score"]:
        return "L"

    elif row["was_home"] == False and row["team_a_score"] > row["team_h_score"]:
        return "W"

    elif row["was_home"] == False and row["team_a_score"] < row["team_h_score"]:
        return "L"

In [ ]:
players_played["result"] = players_played.apply(
    get_result,
    axis=1
)

In [ ]:
players_played["result"].value_counts()

result
L    42021
W    41813
D    24853
Name: count, dtype: int64

In [ ]:
players_played[
    [
        "season",
        "fixture",
        "was_home",
        "team_h_score",
        "team_a_score",
        "name",
        "result"
    ]
].head(20)

,season,fixture,was_home,team_h_score,team_a_score,name,result
1,2016-17,3,True,1.0,1.0,Aaron_Lennon,D
2,2016-17,8,True,3.0,4.0,Aaron_Ramsey,L
5,2016-17,4,True,2.0,1.0,Abel_Hernández,W
6,2016-17,4,True,2.0,1.0,Adama_Diomande,W
7,2016-17,6,True,1.0,1.0,Adam_Clayton,D
9,2016-17,6,True,1.0,1.0,Adam_Forshaw,D
10,2016-17,8,False,3.0,4.0,Adam_Lallana,W
13,2016-17,9,True,1.0,3.0,Adam_Smith,L
14,2016-17,7,False,1.0,1.0,Adlène_Guédioura,D
15,2016-17,5,False,2.0,1.0,Adnan_Januzaj,L
16,2016-17,10,False,2.0,1.0,Adrián_San Miguel del Castillo,L
17,2016-17,4,True,2.0,1.0,Ahmed_Elmohamady,W
18,2016-17,4,False,2.0,1.0,Ahmed_Musa,L
19,2016-17,8,False,3.0,4.0,Alberto_Moreno,W
20,2016-17,6,True,1.0,1.0,Albert_Adomah,D
21,2016-17,5,True,2.0,1.0,Aleksandar_Kolarov,W
23,2016-17,8,True,3.0,4.0,Alexis_Sánchez,L
26,2016-17,8,True,3.0,4.0,Alex_Iwobi,L
28,2016-17,8,True,3.0,4.0,Alex_Oxlade-Chamberlain,L
33,2016-17,9,False,1.0,3.0,Ander_Herrera,W

In [ ]:
import os

os.makedirs("cleaned_data", exist_ok=True)

In [ ]:
players_played.to_csv(
    "cleaned_data/player_appearances_2016_2025.csv",
    index=False
)

In [ ]:
os.path.exists("cleaned_data/player_appearances_2016_2025.csv")

True

In [ ]:
saved_players = pd.read_csv(
    "cleaned_data/player_appearances_2016_2025.csv"
)

saved_players.shape

C:\Users\Admin\AppData\Local\Temp\ipykernel_11588\3233560140.py:1: DtypeWarning: Columns (3: team) have mixed types. Specify dtype option on import or set low_memory=False.
  saved_players = pd.read_csv(

(108687, 17)

In [ ]:
players_played.to_excel(
    "cleaned_data/player_appearances_2016_2025.xlsx",
    index=False
)

In [ ]:
for season, files in season_files.items():
    gw_file, player_file = files

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    print(season, "element_type" in player_info.columns)

NameError: name 'season_files' is not defined

In [ ]:
player_info = pd.read_csv(
    "raw_player_data/2016_players_raw.csv",
    encoding="latin1"
)

"element_type" in player_info.columns

True

In [ ]:
player_info["element_type"].value_counts()

element_type
3    292
2    214
4    104
1     73
Name: count, dtype: int64

In [ ]:
for season, files in season_files.items():
    gw_file, player_file = files

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    print(season, "element_type" in player_info.columns)

NameError: name 'season_files' is not defined

In [113]:
import pandas as pd

In [114]:
players_played = pd.read_csv(
    "cleaned_data/player_appearances_2016_2025.csv",
    low_memory=False
)

players_played.shape

(108687, 17)

In [115]:
players_played.head()

,season,fixture,kickoff_time,team,opponent_team,was_home,team_h_score,team_a_score,element,name,minutes,goals_scored,assists,goals_conceded,clean_sheets,total_points,result
0,2016-17,3,2016-08-13T14:00:00Z,6,17,True,1.0,1.0,142,Aaron_Lennon,15,0,0,0,0,1,D
1,2016-17,8,2016-08-14T15:00:00Z,1,9,True,3.0,4.0,16,Aaron_Ramsey,60,0,0,3,0,2,L
2,2016-17,4,2016-08-13T11:30:00Z,7,8,True,2.0,1.0,163,Abel_Hernández,90,0,1,1,0,5,W
3,2016-17,4,2016-08-13T11:30:00Z,7,8,True,2.0,1.0,164,Adama_Diomande,90,1,0,1,0,8,W
4,2016-17,6,2016-08-13T14:00:00Z,12,14,True,1.0,1.0,283,Adam_Clayton,90,0,0,1,0,2,D

In [116]:
players_played.columns

Index(['season', 'fixture', 'kickoff_time', 'team', 'opponent_team',
       'was_home', 'team_h_score', 'team_a_score', 'element', 'name',
       'minutes', 'goals_scored', 'assists', 'goals_conceded', 'clean_sheets',
       'total_points', 'result'],
      dtype='str')

In [117]:
season_files = {
    "2016-17": ("2016_merged_gw.csv", "2016_players_raw.csv"),
    "2017-18": ("2017-18_merged_gw (1).csv", "2017-18_players_raw (1).csv"),
    "2018-19": ("2018-19_merged_gw (2).csv", "2018-19_players_raw (2).csv"),
    "2019-20": ("2019-20_merged_gw (3).csv", "2019-20_players_raw (3).csv"),
    "2020-21": ("2020-21_merged_gw (4).csv", "2020-21_players_raw (4).csv"),
    "2021-22": ("2021-22_merged_gw (5).csv", "2021-22_players_raw (5).csv"),
    "2022-23": ("2022-23_merged_gw (6).csv", "2022-23_players_raw (6).csv"),
    "2023-24": ("2023-24_merged_gw (7).csv", "2023-24_players_raw (7).csv"),
    "2024-25": ("2024-25_merged_gw (8).csv", "2024-25_players_raw (8).csv"),
    "2025-26": ("2025-26_merged_gw (9).csv", "2025-26_players_raw (9).csv")
}

In [118]:
for season, files in season_files.items():
    gw_file, player_file = files

    player_info = pd.read_csv(
        f"raw_player_data/{player_file}",
        encoding="latin1"
    )

    print(
        season,
        "element_type" in player_info.columns
    )

2016-17 True
2017-18 True
2018-19 True
2019-20 True
2020-21 True
2021-22 True
2022-23 True
2023-24 True
2024-25 True
2025-26 True

In [119]:
players_played.isna().sum()

season            0
fixture           0
kickoff_time      0
team              0
opponent_team     0
was_home          0
team_h_score      0
team_a_score      0
element           0
name              0
minutes           0
goals_scored      0
assists           0
goals_conceded    0
clean_sheets      0
total_points      0
result            0
dtype: int64

In [120]:
master_teams = pd.read_csv(
    "raw_player_data/master_team_list.csv",
    encoding="latin1"
)

master_teams.head(30)

     season  team       team_name
0   2016-17     1         Arsenal
1   2016-17     2     Bournemouth
2   2016-17     3         Burnley
3   2016-17     4         Chelsea
4   2016-17     5  Crystal Palace
5   2016-17     6         Everton
6   2016-17     7            Hull
7   2016-17     8       Leicester
8   2016-17     9       Liverpool
9   2016-17    10        Man City
10  2016-17    11         Man Utd
11  2016-17    12   Middlesbrough
12  2016-17    13     Southampton
13  2016-17    14           Stoke
14  2016-17    15      Sunderland
15  2016-17    16         Swansea
16  2016-17    17           Spurs
17  2016-17    18         Watford
18  2016-17    19       West Brom
19  2016-17    20        West Ham
20  2017-18     1         Arsenal
21  2017-18     2     Bournemouth
22  2017-18     3        Brighton
23  2017-18     4         Burnley
24  2017-18     5         Chelsea
25  2017-18     6  Crystal Palace
26  2017-18     7         Everton
27  2017-18     8    Huddersfield
28  2017-18     9       Leicester
29  2017-18    10       Liverpool

In [121]:
master_teams.columns

Index(['season', 'team', 'team_name'], dtype='str')

In [122]:
for season in players_played["season"].unique():
    teams = players_played.loc[
        players_played["season"] == season,
        "team"
    ].unique()

    print(season, teams)

2016-17 <StringArray>
[ '6',  '1',  '7', '12',  '9',  '2', '15', '20',  '8', '10', '11',  '3',  '5',
 '16', '17', '19', '18', '14',  '4', '13']
Length: 20, dtype: str
2017-18 <StringArray>
['20',  '8',  '1', '18',  '2', '19', '10', '16',  '5',  '6',  '3', '12',  '7',
 '13', '17',  '4', '11', '15', '14',  '9']
Length: 20, dtype: str
2018-19 <StringArray>
[ '4', '10',  '1',  '7', '18',  '9',  '2', '11', '14', '16',  '3', '12', '19',
  '6', '13', '15', '17',  '5', '20',  '8']
Length: 20, dtype: str
2019-20 <StringArray>
['19',  '5',  '3', '12', '18', '10',  '2',  '1', '13',  '6',  '7',  '8', '16',
 '11',  '9', '14',  '4', '15', '17', '20']
Length: 20, dtype: str
2020-21 <StringArray>
[      'Brighton',       'West Ham',  'Sheffield Utd',        'Everton',
         'Fulham',         'Wolves',        'Arsenal',    'Southampton',
      'Liverpool',      'Newcastle',        'Chelsea', 'Crystal Palace',
      'Leicester',          'Spurs',      'West Brom',          'Leeds',
        'Man Utd',        'Burnley',       'Man City',    'Aston Villa']
Length: 20, dtype: str
2021-22 <StringArray>
[   'Southampton',        'Man Utd', 'Crystal Palace',       'Brighton',
        'Everton',       'Man City',          'Leeds',    'Aston Villa',
         'Wolves',        'Chelsea',      'Liverpool',       'West Ham',
        'Watford',        'Norwich',      'Newcastle',      'Leicester',
      'Brentford',        'Arsenal',        'Burnley',          'Spurs']
Length: 20, dtype: str
2022-23 <StringArray>
[   'Southampton',    'Bournemouth',        'Chelsea',      'Newcastle',
      'Leicester',  'Nott'm Forest', 'Crystal Palace',       'West Ham',
      'Liverpool',          'Leeds',         'Fulham',       'Man City',
        'Man Utd',         'Wolves',          'Spurs',       'Brighton',
        'Everton',      'Brentford',    'Aston Villa',        'Arsenal']
Length: 20, dtype: str
2023-24 <StringArray>
[       'Man Utd',      'Brentford',  'Sheffield Utd',      'Liverpool',
        'Chelsea',  'Nott'm Forest',       'Man City',        'Arsenal',
    'Aston Villa',         'Wolves',    'Bournemouth',      'Newcastle',
       'West Ham',        'Burnley',        'Everton',         'Fulham',
 'Crystal Palace',          'Luton',       'Brighton',          'Spurs']
Length: 20, dtype: str
2024-25 <StringArray>
[   'Bournemouth',    'Southampton',    'Aston Villa',         'Wolves',
        'Chelsea',       'Brighton',      'Leicester',  'Nott'm Forest',
        'Arsenal',         'Fulham',        'Ipswich',       'West Ham',
       'Man City',        'Everton',      'Newcastle', 'Crystal Palace',
        'Man Utd',          'Spurs',      'Brentford',      'Liverpool']
Length: 20, dtype: str
2025-26 <StringArray>
[    'Sunderland',       'West Ham',    'Bournemouth',          'Spurs',
      'Liverpool',         'Wolves',         'Fulham',       'Brighton',
        'Everton',       'Man City',          'Leeds',        'Arsenal',
 'Crystal Palace',      'Newcastle',    'Aston Villa',      'Brentford',
        'Man Utd',        'Chelsea',  'Nott'm Forest',        'Burnley']
Length: 20, dtype: str

In [123]:
print(players_played["team"].dtype)
print(master_teams["team"].dtype)

str
int64

In [124]:
master_teams["team"] = master_teams["team"].astype(str)

In [125]:
print(players_played["team"].dtype)
print(master_teams["team"].dtype)

str
str

In [126]:
players_with_teams = players_played.merge(
    master_teams[["season", "team", "team_name"]],
    on=["season", "team"],
    how="left"
)

In [127]:
players_with_teams.shape

(108687, 18)

In [128]:
players_with_teams["team_name"].isna().sum()

np.int64(66671)

In [129]:
players_with_teams.groupby("season")["team_name"].apply(
    lambda x: x.isna().sum()
)

season
2016-17        0
2017-18        0
2018-19        0
2019-20        0
2020-21    10393
2021-22    10485
2022-23    11345
2023-24    11384
2024-25    11566
2025-26    11498
Name: team_name, dtype: int64

In [130]:
players_with_teams["team_name"] = (
    players_with_teams["team_name"]
    .fillna(players_with_teams["team"])
)

In [131]:
players_with_teams["team_name"].isna().sum()

np.int64(0)

In [132]:
players_with_teams.groupby("season")["team_name"].nunique()

season
2016-17    20
2017-18    20
2018-19    20
2019-20    20
2020-21    20
2021-22    20
2022-23    20
2023-24    20
2024-25    20
2025-26    20
Name: team_name, dtype: int64

In [133]:
players_with_teams[
    ["season", "team", "team_name", "name"]
].head(20)

     season team      team_name                            name
0   2016-17    6        Everton                    Aaron_Lennon
1   2016-17    1        Arsenal                    Aaron_Ramsey
2   2016-17    7           Hull                  Abel_Hernández
3   2016-17    7           Hull                  Adama_Diomande
4   2016-17   12  Middlesbrough                    Adam_Clayton
5   2016-17   12  Middlesbrough                    Adam_Forshaw
6   2016-17    9      Liverpool                    Adam_Lallana
7   2016-17    2    Bournemouth                      Adam_Smith
8   2016-17   12  Middlesbrough                Adlène_Guédioura
9   2016-17   15     Sunderland                   Adnan_Januzaj
10  2016-17   20       West Ham  Adrián_San Miguel del Castillo
11  2016-17    7           Hull                Ahmed_Elmohamady
12  2016-17    8      Leicester                      Ahmed_Musa
13  2016-17    9      Liverpool                  Alberto_Moreno
14  2016-17   12  Middlesbrough                   Albert_Adomah
15  2016-17   10       Man City              Aleksandar_Kolarov
16  2016-17    1        Arsenal                  Alexis_Sánchez
17  2016-17    1        Arsenal                      Alex_Iwobi
18  2016-17    1        Arsenal         Alex_Oxlade-Chamberlain
19  2016-17   11        Man Utd                   Ander_Herrera

In [134]:
players_with_teams[
    players_with_teams["season"] == "2024-25"
][["season", "team", "team_name", "name"]].head(20)

,season,team,team_name,name
85623,2024-25,Bournemouth,Bournemouth,Alex Scott
85624,2024-25,Southampton,Southampton,Ben Brereton DÃ­az
85625,2024-25,Aston Villa,Aston Villa,Pau Torres
85626,2024-25,Wolves,Wolves,Hwang Hee-chan
85627,2024-25,Wolves,Wolves,JoÃ£o Victor Gomes da Silva
85628,2024-25,Chelsea,Chelsea,Cole Palmer
85629,2024-25,Brighton,Brighton,Mitoma Kaoru
85630,2024-25,Leicester,Leicester,Boubakary SoumarÃ©
85631,2024-25,Nott'm Forest,Nott'm Forest,Chris Wood
85632,2024-25,Bournemouth,Bournemouth,Milos Kerkez
85633,2024-25,Brighton,Brighton,Jason Steele
85634,2024-25,Nott'm Forest,Nott'm Forest,Ibrahim SangarÃ©
85635,2024-25,Brighton,Brighton,Adam Webster
85636,2024-25,Arsenal,Arsenal,Thomas Partey
85637,2024-25,Fulham,Fulham,Harry Wilson
85638,2024-25,Leicester,Leicester,Kasey McAteer
85639,2024-25,Ipswich,Ipswich,Wes Burns
85640,2024-25,West Ham,West Ham,Max Kilman
85641,2024-25,Man City,Man City,SÃ¡vio 'Savinho' Moreira de Oliveira
85642,2024-25,West Ham,West Ham,Emerson Palmieri dos Santos

In [135]:
players_with_teams.to_csv(
    "cleaned_data/player_appearances_cleaned_v2.csv",
    index=False
)

players_with_teams.to_excel(
    "cleaned_data/player_appearances_cleaned_v2.xlsx",
    index=False
)

In [136]:
import os

print(os.path.exists(
    "cleaned_data/player_appearances_cleaned_v2.csv"
))

print(os.path.exists(
    "cleaned_data/player_appearances_cleaned_v2.xlsx"
))

True
True